version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: grievance_user
      POSTGRES_PASSWORD: strongpassword
      POSTGRES_DB: grievance_db
    ports:
      - "5432:5432"
